[package]
name = "evalpy"
version = "0.1.0"
edition = "2021"

[lib]
name = "evalpy"
crate-type = ["cdylib"]

[dependencies]
ss_analysis = { path = "../ss_analysis" }

[dependencies.pyo3]
 version = "0.17"
 features = ["extension-module"]